name: housing
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.0
  - scikit-learn=1.4.0

  # API
  - fastapi=0.109.0
  - uvicorn=0.27.0
  - pydantic=2.5.3
  - httpx=0.27.0

  # API test script
  - requests=2.32.5

  # Testing (optional but useful)
  - pytest=8.0.0

